Add support for Elastic 8
newrelic/nri-elasticsearch pull request #137
Opened 2023-01-09 10:46 UTC by carlossscastro

Update tests and deprecate metrics in ES8

Metrics dropped:
- "threadpool.indexActive"
- "threadpool.indexQueue"
- "threadpool.indexRejected"
- "threadpool.indexThreads"
- "threadpool.listenerActive"
- "threadpool.listenerQueue"
- "threadpool.listenerRejected"
- "threadpool.listenerThreads"

2023-01-11 12:24 UTC, marcsanmi commented on tests/integration/elasticsearch_test.go
>  // +build integration
Can we remove the old build tag format?

2023-01-11 15:41 UTC, carlossscastro commented on tests/integration/elasticsearch_test.go
>  // +build integration
👍 Thanks for spotting this

2023-01-17 09:48 UTC, paologallinaharbur commented on tests/integration/docker-compose.yml
> +    image: elasticsearch:8.5.3
would make sense to add a test for the lowest version we support?

If it is not that easy or it would add too much time to the ci/cd ignore this :)

2023-01-17 14:04 UTC, paologallinaharbur commented on tests/integration/docker-compose.yml
> +      - discovery.seed_hosts=elasticsearch2
is elasticsearch2 the name of the replica? can we change its name?

2023-01-17 14:05 UTC, paologallinaharbur commented on tests/integration/json-schema-files/elasticsearch-schema.json
> -                  },
before merging this we might want to create the Pr for the docs

2023-01-17 14:05 UTC, paologallinaharbur approved these changes
Thanks for taking care of this!

2023-01-17 14:43 UTC, paologallinaharbur requested changes
We agreed offline to keep ThreadPoolListener since it is still present in version 7 although deprecated.

2023-01-17 15:42 UTC, carlossscastro commented on tests/integration/docker-compose.yml
> +      - discovery.seed_hosts=elasticsearch2
yes. Name changed to `elasticsearch-replica`

2023-01-17 15:43 UTC, carlossscastro commented on tests/integration/json-schema-files/elasticsearch-schema.json
> -                  },
Will PR the docs once this is merged making note that `threadpool.listener` metrics are only reported on version 7 and totally deprecated after that

2023-01-17 15:45 UTC, carlossscastro commented on tests/integration/docker-compose.yml
> +    image: elasticsearch:8.5.3
we agreed that the only difference between 7 and 8 is the presence of the already deprecated `threadpool.listener` metrics, so no need to duplicated tests and schema files for those

2023-01-18 09:06 UTC, paologallinaharbur approved these changes

2023-01-18 09:07 UTC, paologallinaharbur commented on src/metric_definition.go
>  }
you are missing the changelog :)

2023-01-19 12:53 UTC, carlossscastro commented on src/metric_definition.go
>  }
Changelog Updated 👍

2023-01-19 12:54 UTC, carlossscastro commented
Documentation update: https://github.com/newrelic/docs-website/pull/11099

2023-01-19 14:44 UTC, merged